# Generated by Django 2.2.13 on 2020-06-12 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customtext_hgfjhgfjgjgwwwwwwwqq'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='ghmgfhguuuuuuuuwww',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customtext_ghmgfhguuuuuuuuwww', to='home.CustomText'),
        ),
    ]
